Repository Frachtwerk/essencium-backend, pull requests merged in 2024-04, with the labels that each got.

#362 feat: Make JPA-Table-Name-Style configurable, Allow disabling Upper-Case-Table-Names
  CHANGELOG.md
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/configuration/DataNamingConfig.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/configuration/properties/AppConfigJpaProperties.java
Labels: enhancement

#367 fix: An expired but still existing SessionToken throws an Internal Server Error (HTTP 500)
  CHANGELOG.md
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/service/JwtTokenService.java
Labels: bug

#369 368 validating existence of default role fails when not defined in environment
  CHANGELOG.md
  essencium-backend-development/src/main/java/de/frachtwerk/essencium/backend/configuration/initialization/RoleInitializer.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/configuration/initialization/DefaultRoleInitializer.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/model/Role.java
  essencium-backend/src/test/java/de/frachtwerk/essencium/backend/configuration/initialization/DefaultRoleInitializerTest.java
  essencium-backend/src/test/java/de/frachtwerk/essencium/backend/configuration/initialization/TestRoleInitializer.java
Labels: bug

#329 106 an admin should not be able to delete own account
  CHANGELOG.md
  essencium-backend-identity-model/src/main/java/de/frachtwerk/essencium/backend/service/UserService.java
  essencium-backend-sequence-model/src/main/java/de/frachtwerk/essencium/backend/service/UserService.java
  essencium-backend-uuid-model/src/main/java/de/frachtwerk/essencium/backend/service/UserService.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/configuration/initialization/DefaultRoleInitializer.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/configuration/properties/RoleProperties.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/model/AbstractBaseUser.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/service/AbstractUserService.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/service/RoleService.java
  essencium-backend/src/test/java/de/frachtwerk/essencium/backend/configuration/initialization/DefaultRoleInitializerTest.java
  essencium-backend/src/test/java/de/frachtwerk/essencium/backend/service/LongUserService.java
  essencium-backend/src/test/java/de/frachtwerk/essencium/backend/service/LongUserServiceTest.java
  essencium-backend/src/test/java/de/frachtwerk/essencium/backend/service/UUIDUserService.java
  essencium-backend/src/test/java/de/frachtwerk/essencium/backend/service/UUIDUserServiceTest.java
  essencium-backend/src/testIntegration/java/de/frachtwerk/essencium/backend/test/integration/controller/AuthenticationControllerIntegrationTest.java
  essencium-backend/src/testIntegration/java/de/frachtwerk/essencium/backend/test/integration/controller/UserControllerIntegrationTest.java
  essencium-backend/src/testIntegration/java/de/frachtwerk/essencium/backend/test/integration/service/TestUserService.java
  essencium-backend/src/testIntegration/java/de/frachtwerk/essencium/backend/test/integration/util/TestingUtils.java
Labels: bug

#411 fix: replace reference comparison by value comparison
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/service/AbstractUserService.java
Labels: bug

#419 Upgrade dependencies 04 2024
  CHANGELOG.md
  essencium-backend-development/pom.xml
  essencium-backend-identity-model/pom.xml
  essencium-backend-sequence-model/pom.xml
  essencium-backend-uuid-model/pom.xml
  essencium-backend/pom.xml
Labels: dependencies, java

#408 chore: ignore invalid rights from properties
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/configuration/initialization/DefaultRoleInitializer.java
  essencium-backend/src/main/java/de/frachtwerk/essencium/backend/service/RightService.java
  essencium-backend/src/test/java/de/frachtwerk/essencium/backend/configuration/initialization/DefaultRoleInitializerTest.java
Labels: bug
